# Generated by Django 4.0 on 2021-12-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etag', models.CharField(max_length=100)),
                ('channelId', models.CharField(max_length=100)),
                ('channelTitle', models.CharField(max_length=100)),
                ('publishedAt', models.DateTimeField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=100)),
            ],
        ),
    ]
