# Generated by Django 4.0 on 2021-12-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etag', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_title', models.CharField(db_index=True, max_length=100)),
                ('published_at', models.DateTimeField(db_index=True, max_length=100, null=True)),
                ('thumbnail_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
