# Generated by Django 4.0 on 2021-12-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_explore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='channelId',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='channelTitle',
            new_name='channel_title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='publishedAt',
            new_name='published_at',
        ),
    ]
