response_json = {'etag': 'R-m270fjCyRXX_kEDgMJxzOdo14',
 'items': [{'etag': 'EvCm18eGEwPS2NgyA53XaCI5dO8',
            'id': {'kind': 'youtube#video', 'videoId': '4k09uMGGy6o'},
            'kind': 'youtube#searchResult',
            'snippet': {'channelId': 'UClrFMiY-Gle5LUa571eyQQg',
                        'channelTitle': 'Ark Of Grace Ministries',
                        'description': 'We Serve An Awesome God! You can '
                                       'follow Noble the Pig and all his '
                                       'adventures: Instagram: Piggynoble1 '
                                       'twitter:NobletheP YOU ...',
                        'liveBroadcastContent': 'live',
                        'publishTime': '2021-12-29T22:51:40Z',
                        'publishedAt': '2021-12-29T22:51:40Z',
                        'thumbnails': {'default': {'height': 90,
                                                   'url': 'https://i.ytimg.com/vi/4k09uMGGy6o/default_live.jpg',
                                                   'width': 120},
                                       'high': {'height': 360,
                                                'url': 'https://i.ytimg.com/vi/4k09uMGGy6o/hqdefault_live.jpg',
                                                'width': 480},
                                       'medium': {'height': 180,
                                                  'url': 'https://i.ytimg.com/vi/4k09uMGGy6o/mqdefault_live.jpg',
                                                  'width': 320}},
                        'title': 'Amanda Grace Talks..LIVE WITH CLAY: CHINA, '
                                 'PROPECHY AND TECHNOLOGY'}},
           {'etag': '8f2hLnj8rGtAMcZZBUCcps4BPZE',
            'id': {'kind': 'youtube#video', 'videoId': 'f4fMIe7z2eE'},
            'kind': 'youtube#searchResult',
            'snippet': {'channelId': 'UCzoZ_aiAcpM7F4X7Zimnd8A',
                        'channelTitle': 'Super Soldier Talk',
                        'description': 'Arcturus Ra is a Starseed and Cosmic '
                                       'Agent who has volunteered to assist '
                                       'humanity in raising its planetary '
                                       'frequency. Arcturus ...',
                        'liveBroadcastContent': 'none',
                        'publishTime': '2021-12-29T22:52:24Z',
                        'publishedAt': '2021-12-29T22:52:24Z',
                        'thumbnails': {'default': {'height': 90,
                                                   'url': 'https://i.ytimg.com/vi/f4fMIe7z2eE/default.jpg',
                                                   'width': 120},
                                       'high': {'height': 360,
                                                'url': 'https://i.ytimg.com/vi/f4fMIe7z2eE/hqdefault.jpg',
                                                'width': 480},
                                       'medium': {'height': 180,
                                                  'url': 'https://i.ytimg.com/vi/f4fMIe7z2eE/mqdefault.jpg',
                                                  'width': 320}},
                        'title': 'Super Soldier Talk – Arcturus Ra – Cosmic '
                                 'Agent – Healing Technology'}},
           {'etag': 'h9Dnmar-oRLy_MJ-3z1Z6aFTaRo',
            'id': {'kind': 'youtube#video', 'videoId': '24IduHKwz7k'},
            'kind': 'youtube#searchResult',
            'snippet': {'channelId': 'UCJekgf6k62CQHdENWf2NgAQ',
                        'channelTitle': 'Wolfram',
                        'description': 'Stephen Wolfram hosts a live and '
                                       'unscripted Ask Me Anything about the '
                                       'history of science and technology for '
                                       'all ages. Find the ...',
                        'liveBroadcastContent': 'none',
                        'publishTime': '2021-12-29T22:12:18Z',
                        'publishedAt': '2021-12-29T22:12:18Z',
                        'thumbnails': {'default': {'height': 90,
                                                   'url': 'https://i.ytimg.com/vi/24IduHKwz7k/default.jpg',
                                                   'width': 120},
                                       'high': {'height': 360,
                                                'url': 'https://i.ytimg.com/vi/24IduHKwz7k/hqdefault.jpg',
                                                'width': 480},
                                       'medium': {'height': 180,
                                                  'url': 'https://i.ytimg.com/vi/24IduHKwz7k/mqdefault.jpg',
                                                  'width': 320}},
                        'title': 'History of Science and Technology Q&amp;A '
                                 '(December 29, 2021)'}},
           {'etag': 'Hip2WG4u7Eqi9h_Q_-H9fqolI60',
            'id': {'kind': 'youtube#video', 'videoId': 'W5NaEoQapRI'},
            'kind': 'youtube#searchResult',
            'snippet': {'channelId': 'UC34_SxzRr7FOYdKfjLpVBzw',
                        'channelTitle': 'Matt Borchert',
                        'description': 'What the Metaverse is and Why You '
                                       'Should Care! Protect Your NFTs With a '
                                       'Ledger Wallet ...',
                        'liveBroadcastContent': 'none',
                        'publishTime': '2021-12-29T21:42:15Z',
                        'publishedAt': '2021-12-29T21:42:15Z',
                        'thumbnails': {'default': {'height': 90,
                                                   'url': 'https://i.ytimg.com/vi/W5NaEoQapRI/default.jpg',
                                                   'width': 120},
                                       'high': {'height': 360,
                                                'url': 'https://i.ytimg.com/vi/W5NaEoQapRI/hqdefault.jpg',
                                                'width': 480},
                                       'medium': {'height': 180,
                                                  'url': 'https://i.ytimg.com/vi/W5NaEoQapRI/mqdefault.jpg',
                                                  'width': 320}},
                        'title': 'What is the Metaverse? - Diving into the '
                                 'Technology, NFTs, and the Future!'}},
           {'etag': 'gZKO1wm4IWqzDFBE8uigDswC5yk',
            'id': {'kind': 'youtube#video', 'videoId': 'c_2-DOP9Mlg'},
            'kind': 'youtube#searchResult',
            'snippet': {'channelId': 'UChas49rrzl5D06Ccv1NGWUg',
                        'channelTitle': 'HASNAT KHAN',
                        'description': 'Saudi Arabia is getting modern '
                                       'technology from China। 2021 Hello '
                                       'Friends, I am Hasnat Khan, Welcome to '
                                       'My Channel, ...',
                        'liveBroadcastContent': 'none',
                        'publishTime': '2021-12-29T20:39:27Z',
                        'publishedAt': '2021-12-29T20:39:27Z',
                        'thumbnails': {'default': {'height': 90,
                                                   'url': 'https://i.ytimg.com/vi/c_2-DOP9Mlg/default.jpg',
                                                   'width': 120},
                                       'high': {'height': 360,
                                                'url': 'https://i.ytimg.com/vi/c_2-DOP9Mlg/hqdefault.jpg',
                                                'width': 480},
                                       'medium': {'height': 180,
                                                  'url': 'https://i.ytimg.com/vi/c_2-DOP9Mlg/mqdefault.jpg',
                                                  'width': 320}},
                        'title': 'Saudi Arabia is getting modern technology '
                                 'from China। 2021'}}],
 'kind': 'youtube#searchListResponse',
 'nextPageToken': 'CAUQAA',
 'pageInfo': {'resultsPerPage': 5, 'totalResults': 1000000},
 'regionCode': 'IN'}